apiVersion: v1
kind: Service
metadata:
  name: svc-2x8xa100-80gb
spec:
  clusterIP: None
  selector:
    app: 2x8xa100-80gb
  ports:
  # Expose the port for vllm LLM inference API calling.
    - name: dist
      port: 29500
      targetPort: 29500
    - name: http
      port: 8000
      targetPort: 8000
